version: "3.4"
services:
  backend:
    build: .
    networks:
      - place-net

  redis:
    image: redis
    networks:
      - place-net

  cassandra:
    image: cassandra
    networks:
      - place-net

networks:
  place-net:
